### ISSUE TITLE
Vocabulary component

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#10]
Currently, we are partially integrating the vocabulary. There are some methods, but we also have more methods in the independent vocabulary repository. However, separating the case base and the vocabulary into two libraries/repositories was more blocking than helpful.
Because of this fact, both repositories should be merged, and the vocabulary component should be reworked from scratch also to follow the new library structure.

## To-Dos

- [x] Archive the vocabulary repository
- [x] Create a new vocabulary class
- [x] Implement new methods shown in the features section down below
- [x] #21
- [x] Implement Vocabulary Loader
- [x] Create the conditions class
- [x] Add tests

## Features
**new_vocabulary()**

- Creates a new vocabulary from scratch
- Params: _version_ of the int
- Returns: Vocabulary

**load_vocabulary()**

- Loads an existing vocabulary from a TOML using the vocabulary definition structure
- Params: _file_path_ of the string
- Returns: Vocabulary

**generate_vocabulary_from_data()**

- Generate a vocabulary from a defined data source
- Params: _data_ of type list(dict)
- Returns: Vocabulary

### Vocabulary Class
**add_attribute()**

- Adds a new attribute to the vocabulary
- Params: _key_ (string), _data_type_ (type of either int, float or numerical vector), _conditions_ (Conditions), _type_ (string of either feature or target)
- Returns: None (the method changes the instance directly)

**save()**

- Saves the current vocabulary definition in the program into a file where it can be stored for a longer time
- Params: _destination_ (file path as string)
- Returns: None

### Conditions
Users can define conditions for attributes in a case which are used to validate a case. Whenever the case base is loaded or a new case is added to the case base, the library will validate the case or cases. Cases with invalid values will be flagged.

**Operators**
- equals
- not equals
- greater than
- greater than equals
- lower than
- lower than equals
