### ISSUE TITLE
Case Base Maintainer Component

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#11]
The Case Base Maintainer manages tasks related to the case base. It should be able to add data to the case base, update the cases, and remove cases that aren't improving the system's performance.

## To-Dos

- [ ] Case Base class
- [ ] Implement methods for CB class which are listed in the features section below
- [ ] Data Source Adapter for CB class to interact with the actual data source (when removing unused cases or increasing the utility count)
- [ ] Implement validator that validates the conditions provided by the vocabulary
- [ ] Implement method that fills empty columns with 0s

## Features
**add_data()**

- Add data to the case base of the instance
- Params: _data_ (list of cases), _validate_ (boolean), _fill_empty_ (boolean)
- Returns: None

**update_utils()**

- Increase the utils count for the specific case
- The utils count increases whenever the case was used to solve another case
- This means that the util count is a performance measurement for a case
- Params: _case_
- Returns: None

**prune()**

- Removes cases from the case base that meet a specific criteria (e.g. util score)
- Params: _threshold_ (int)
- Returns: None

**Comment by jonasliendl** [comment]
@junkratjannek I've added a new method to implement for the case-base class.
