### ISSUE TITLE
Semantic Distance Algorithm

### ISSUE THREAD

**Issue by LukasKlockenhoff** [Case-Based/casebased#12]
We need to support semantic distance between words so we can calculate differences between words and sentences while keeping the meaning of the word in mind?

dist("Haus", "Maus") < dist("Haus", "Villa")

Der Nutzer muss hier die wörter umwandeln und selber ein tool einbinden aber wir müssen mindestens die schnittstelle liefern.

## To-Dos

- [ ] Research Libraries / tools for this job
- [ ] Support words in the case base
- [ ] Create Interface to Semantic tool
- [ ] Alter behaviour of retrieval algorithm
- [ ] error handling and alerting the user to the need for semantic distance.
- [ ] Add tests

## Features
**attach_handler()**

- attach semantic distance handler to instance

...?
