### ISSUE TITLE
Weights and the learning of it

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#13]
For a precise machine learning model, the weights cannot be defined manually. This is why we have to come up with another approach where the weights are getting learned by for example an artificial neural network that looks through the case base and defines the weights based on the solutions there.

## To-Dos

- [ ] Research for ANNs
- [ ] Find a fitting model
- [ ] Embed model into library
- [ ] Implement method to learn the weights and define them for cases
- [ ] Add tests
