### ISSUE TITLE
Adaptation rules

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#14]
In order to solve a case we need adaptation rules that adapt the existing solutions in the case base to the new case. 

## To-Dos

- [ ] Research adaptation rules
- [ ] Create information sheet with all adaptation rules the library should support
- [ ] Implement adaptation rules
- [ ] Add tests for the adaptation rules

### Quick Overview of possible adaptation rules

- Substitution Adaptation
- Structural Adaptation
- Derivational Adaptation
- Heuristic Adaptation
- Reinstantiation Adaptation
- Rule-Based Adaptation
- Parametric Adaptation
- Abstraction-Based Adaptation
- Specialization-Based Adaptation
- Blended Adaptation
- Transformation-Based Adaptation
