### ISSUE TITLE
Similarity Measure Component

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#15]
Before we can solve a case, we have to retrieve the most similar cases. These cases are used to find a solution for the new case. For this search, we use the k-nearest-neighbor algorithm with a defined distance measurement algorithm. Some of these algorithms are built-in; however, users can also define custom functions that calculate the distance.

## To-Dos

- [x] Research distance measurement algorithms
- [x] Find the best algorithms for built-in algorithms
- [x] Implement similarity measure component
- [ ] Add tests for component

### Similarity Measure
The similarity measure component is responsible for the entire similarity calculation between all cases. The goal is to make this component highly customizable so users can provide custom measurement and k-finding algorithms.

**calculate_distance()**

- Calculates the distance between two cases
- Uses the custom similarity measure algorithm from the local SimilarityMeasure instance
- The KNN algorithm uses this method
- Params: _self_, _case_0_ (list), _case_1_ (list)
- Returns: int
