### ISSUE TITLE
Complete rework of the library structure

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#9]
With the new approach we discussed, we have to rework the entire library structure. We are moving from independent components to one specific component with whom users can create instances.
After initialization, users can use this instance's methods to load the case base, solve a case, validate the case base, and much more.

## To-Dos
- [x] From executable structure to library structure
- [x] Case-Base class that unifies all components of the CBR system
- [x] Configuration class for case base instance
- [x] Method to add config to case-base instance
- [x] Add tests

### Case-Base Class
**new_instance()** 
- Create a new case-base system instance
- Params: _configuration_ with type Configuration instance (optional)
- Returns: CaseBaseSystem

**update_config()**
- Update configuration on runtime
- Params: _new_config_ with type Configuration instance
- Returns: None (void)

### Configuration Dataclass
The configuration is used to define how the system should behave or calculate stuff. 
**Attributes:**
- Similarity Measure Algorithm (Euclidean, Manhattan, Cosine, etc.) also custom measurements (lambda function)
- Algorithm to define K for KNN (Elbow, BIC, etc.) also custom by using lambda function
- K (int) which is manually defined

**Comment by LukasKlockenhoff** [comment]
@jonasliendl hab reviewed bitte den Legacy code erstmal noch supported solange keine alternative gepusht wird damit wir immer nur functionality addieren und den anhaltspunkt nutzen können. -> #16

**Comment by LukasKlockenhoff** [comment]
Closing this as DONE!
